### ISSUE TITLE
yo yo

### ISSUE THREAD

**Issue by PatrickJS** [bahmutov/node-rx-cycle#1]
you should also checkout a project a friend and I thought up a couple years ago (when we discovered rx) https://github.com/aychtang/reiki

**Comment by bahmutov** [comment]
nice, I remember seeing this! 
But my repo is just demo code for the blog post that explains reactive server implementation and then the cycle.js abstraction and how it applies to the server instead of the user interface.

**Comment by PatrickJS** [comment]
sounds good, looking forward to it :+1:
