### ISSUE TITLE
Server stops to responding further request after all delayed events have been delivered.

### ISSUE THREAD

**Issue by jacobbubu** [bahmutov/node-rx-cycle#2]
I think these lines of code lead to the problem.
https://github.com/bahmutov/node-rx-cycle/blob/master/src/rate-limit.js#L32-L34

**Comment by bahmutov** [comment]
I think I put this as a feature to complete the stream

**Comment by jacobbubu** [comment]
How about change it in this way:

``` js
   var completed = false;
   function onCompleted() {
      completed = true
   }
   ...
   setTimeout(function () {
      debug('sending', e, 'at', +(new Date()) - started)
      out_.onNext(e)
      hasEvents -= 1
      if (!hasEvents && completed) {
         out_.onCompleted()
      }
   }, sleepMs)
```

**Comment by bahmutov** [comment]
but why would this be needed? The way it is done now is to show this particular example for the corresponding blog post, which shows the stream complete event

**Comment by jacobbubu** [comment]
I've read through the blog post, but I'm not sure this is your intended design by closing the reateLimit (out_) streamahead of the `requests_` stream. 

The further request in requests_` stream will go no where when the reateLimit  stream has been closed (completed) that caused by your original design (complete the reateLimite stream when all the delayed requests has been sent out).

**Comment by bahmutov** [comment]
you might be right. If I make the rate limit into its own library or utility, I will definitely need to test it well and think about the design
